### ISSUE TITLE
Weird regression wrt to host's CC

### ISSUE THREAD

**Issue by rubdos** [ncalexan/rust-android-gradle#17]
Hi, it's me again.

I get the same kind of errors as in #15 , so this might be related. This time, the error (`clang` returned -1) did not get solved by deleting the toolchain dir. I noticed that during the building of the **build script**:

```
error: failed to run custom build command for `libloading v0.5.0`
process didn't exit successfully: `/home/rsmet/src/GlycosBindingTest/backend/target/debug/build/libloading-1a65a054dc2cfbc5/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=dl
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("/tmp/rust-android-ndk-toolchains/arm-21/bin/arm-linux-androideabi-clang")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
```

`HOST_CC` is not set. `bindgen`/`clang-sys` tries to run the `arm-linux-androideabi-clang` *for the build script*:

```
Internal error occurred: Command "/tmp/rust-android-ndk-toolchains/arm-21/bin/arm-linux-androideabi-clang" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=x86_64-unknown-linux-gnu" "-Wall" "-Wextra" "-o" "/home/rsmet/src/GlycosBindingTest/backend/target/debug/build/libloading-9e16774041d283e1/out/src/os/unix/global_static.o" "-c" "src/os/unix/global_static.c" with args "arm-linux-androideabi-clang" did not execute successfully (status code exit code: 1).
```

~~Mind that I'm using my windows-patches branch currently to circumvent #7, but I can reproduce this on your 0.4.1 version too.~~

```sh
export HOST_CC=/usr/bin/gcc
```

works around this issue. Maybe we should set `HOST_CC` in `rust-android-gradle`?

**Comment by ncalexan** [comment]
I think that we shouldn't be forcing `CC` (or `AR`) globally at all around https://github.com/ncalexan/rust-android-gradle/blob/6d54d5afda3762a7d8f505eeb00d01407a9b79d5/plugin/src/main/kotlin/com/nishtahir/CargoBuildTask.kt#L115-L116.  We should be setting Rust target specific variables, like:
```kotlin
environment("CARGO_TARGET_${toolchain.target.toUpperCase().replace('-', '_')}_LINKER", "$cc");
```
I have similar work to try to make the linker specification better, but could you investigate if this can solve the issue locally?  I really don't want to set `HOST_*`; that should be passed through if the consumer sets it.  Tricky stuff, this -- Cargo is configurable, but not _that_ configurable.

**Comment by ncalexan** [comment]
@rubdos I landed a patch that should address this in the new 0.6.0 release.  Let me know if I've just made things worse :/

**Comment by rubdos** [comment]
I would've checked yesterday around this time, but I couldn't reproduce this anymore. There must've been something really wacky.

Thank you for the invitation. I've gladly accepted, and I will try to contribute where I can.

Your 0.6.0 seems to work on Linux. I am testing on Windows now.
