### ISSUE TITLE
Doesn't find cargo when installed in ~/.cargo

### ISSUE THREAD

**Issue by bbqsrc** [ncalexan/rust-android-gradle#18]
By default it seems that Gradle can't find `cargo` even though it's in the `PATH` env var in the terminal in which I run `./gradlew`. What am I doing wrong?

**Comment by ncalexan** [comment]
@bbqsrc you should be able to set this in `local.properties` or via the environment with the new 0.6.0 release.  Can you let me know if you still have issues?  Thanks!
