### ISSUE TITLE
WARNING:__main__:make_standalone_toolchain.py is no longer necessary.

### ISSUE THREAD

**Issue by rubdos** [ncalexan/rust-android-gradle#37]
It seems like generating standalone toolchains in not necessary any more as of a certain NDK version.

```
WARNING:__main__:make_standalone_toolchain.py is no longer necessary. The
$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin directory contains target-specific scripts that perform
the same task. For example, instead of:

    $ python $NDK/build/tools/make_standalone_toolchain.py \
        --arch arm --api 24 --install-dir toolchain
    $ toolchain/bin/clang++ src.cpp

Instead use:

    $ $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang++ src.cpp
```

Sounds to me like this would reduce build times by a bit, and would reduce the complexity of the `rust-android-gradle` plugin! Seems also like it would fix things like #15, since it removes the need for toolchain dirs.

(I couldn't find an issue describing this yet, feel free to close if I looked over it.)

**Comment by thomcc** [comment]
You're looking for https://github.com/mozilla/rust-android-gradle/#prebuilttoolchains

**Comment by rubdos** [comment]
... it's even documented. Sorry for the noise, thanks for the link!
