### ISSUE TITLE
`ANDROID_NDK_TOOLCHAIN_DIR` discussion

### ISSUE THREAD

**Issue by rubdos** [ncalexan/rust-android-gradle#7]
Is there a specific reason that this `ANDROID_NDK_TOOLCHAIN_DIR` variable is made mandatory? I think it would be nice to be able to specify it in the gradle build file, and still default to some temporary directory.

( https://github.com/ncalexan/rust-android-gradle/commit/d6f70b381305ca299dbd2c62badd1fe0a67cb86f )

EDIT: I think the main annoyance is for people that use Android Studio: they would have to globally set an environment variable, instead of "configuring" it locally. The toolchains aren't that heavy either, they install here in a matter of milliseconds.

**Comment by thomcc** [comment]
When specified, it's pretty likely to be a path specific to a given machine and not the kind of thing you'd want in a version controlled build file.

That said I don't have strong feelings about this, it makes sense to me that if the toolchains do install quickly (for some reason I remember this not being the case for me, but i could be wrong...), that we make it optional and default to a temp dir.

**Comment by rubdos** [comment]
> When specified, it's pretty likely to be a path specific to a given machine and not the kind of thing you'd want in a version controlled build file.

I agree with this, and gave it more thought since I wrote this comment. What if we make it possible to specify it in the `local.properties` file? This file should not be checked in into version control, and is machine specific already.

I still think defaulting to a standard temp location would be quite okay. I've tested this under a Windows machine with a HDD, and it only took a few seconds to make four toolchains. I think they are just precompiled and shipped with the NDK these days.

**Comment by ncalexan** [comment]
> I still think defaulting to a standard temp location would be quite okay (on top of the above). I've tested this under a Windows machine with a HDD, and it only took a few seconds to make four toolchains. I think they are just precompiled and shipped with the NDK these days.

Yes, making the standalone toolchains is not expensive, since it's just manipulating existing files on disk.



> I agree with this, and gave it more thought since I wrote this comment. What if we make it possible to specify it in the `local.properties` file? This file should not be checked in into version control, and is machine specific already.

So, fun fact: `local.properties` is totally non-standard; it doesn't integrate into the Gradle properties ecosystem at all.  That doesn't mean we can't use it, just that it's something one must manually parse, etc.  I'd be very happy to put the toolchain location in `local.properties` and default to a temp directory that is platform appropriate.

**Comment by rubdos** [comment]
Another thought: if we don't like integrating `local.properties` (because non-standard), we could offer a configuration option in the `cargo { ... }` and then have example code reading it from `local.properties`? What would be the preferred way?

**Comment by rubdos** [comment]
Another thought: if we go with a Gradle config option, we can make use of

> Setting up a consistent environment for your build is as simple as placing these settings into a gradle.properties file. The configuration is applied in following order (if an option is configured in multiple locations the last one wins):
>
>    gradle.properties in project root directory.
>
>    gradle.properties in GRADLE_USER_HOME directory.
>
>    system properties, e.g. when -Dgradle.user.home is set on the command line.

This can give users a system wide option for the NDK_TOOLCHAIN thing, without needing it in their environment... Just spewing random thoughts.

**Comment by ncalexan** [comment]
I think this is done as of e81a7cae967d82b86b79eee09d1b2ad072c49e79.  We could definitely more options if we need them.
